### ISSUE TITLE
Create cards for "Basics"

### ISSUE THREAD

**Issue by vrlevc** [vrlevc/java_tutorial#5]
- [x] Getting Started.
- [x] Learning the Java Language.
- [x] Essential Java Classes.
- [x] Collections.
- [x] Date-Time APIs.
- [x] Deployment.

**Comment by vrlevc** [comment]
Done.
